"""added Project model

Revision ID: f998ec2e4f0f
Revises: 
Create Date: 2025-05-02 10:17:05.099858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f998ec2e4f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_one', sa.String(length=8), nullable=False),
    sa.Column('student_two', sa.String(length=8), nullable=False),
    sa.Column('student_three', sa.String(length=8), nullable=False),
    sa.Column('student_four', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
